name: Vincent Mark CICD for booking to aws ec2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    name: Backend deployment CICD
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup node
        run: |
          npm install
          npm run start

        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            . ~/.nvm/nvm.sh

            nvm install 16
            nvm use 16
            git config --global --add safe.directory ${{ secrets.DIRECTORY }}
            cd ${{ secrets.DIRECTORY }}
            git pull https://${{ secrets.UNAME }}:${{ secrets.PASSWORD }}@${{ secrets.BGIT }} main
            pm2 stop index.js
            pm2 start index.js
